services:
  frontend:
    build: ./Frontend
    container_name: zonetyper-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    depends_on:
      - backend
  
  backend:
    build: ./Backend
    container_name: zonetyper-backend
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Host=postgres;
      - Port=5432;Database=${POSTGRES_DB};
      - Username=${POSTGRES_USER};
      - Password=${POSTGRES_PASSWORD}
    depends_on:
      - postgres
  
  postgres:
    image: postgres:16
    container_name: zonetyper-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: