// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ZonetyperApi.Migrations
{
    [DbContext(typeof(ZonetyperDbContext))]
    partial class ZonetyperDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ZonetyperApi.Models.Keystroke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<char>("CharacterTyped")
                        .HasColumnType("character(1)");

                    b.Property<char>("ExpectedCharacter")
                        .HasColumnType("character(1)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("TimestampMs")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Keystrokes");
                });

            modelBuilder.Entity("ZonetyperApi.Models.SourceText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SourceTexts");
                });

            modelBuilder.Entity("ZonetyperApi.Models.TypingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Accuracy")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Duration")
                        .HasColumnType("integer");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer");

                    b.Property<int>("PromptId")
                        .HasColumnType("integer");

                    b.Property<double>("RawWPM")
                        .HasColumnType("double precision");

                    b.Property<Guid>("SessionGuid")
                        .HasColumnType("uuid");

                    b.Property<double>("WPM")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("TypingSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
